# Use https://app.stepsecurity.io/ to improve workflow security
name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:
    name: Go Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, macos-14, windows-latest]
        version: [stable, oldstable]
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Install make (Windows)
      if: runner.os == 'Windows'
      run: choco install -y make mingw

    - name: Check OpenAPI
      if: runner.os == 'Linux'
      run: make check-openapi

    - name: Check
      run: make check
      env:
        GOLANGCI_LINTERS: gosec

    - name: WebUI
      run: make build-webui

  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: stable
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Docker Build
      run: make docker

    - name: Docker Tests
      run: make test-integration

    - name: Cleanup
      run: make clean-integration
